/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-tint': '#89ceff',
        'surface-container-low': '#191b21',
        'secondary-fixed-dim': '#ffb690',
        'on-primary-fixed-variant': '#004c6e',
        'on-secondary-fixed': '#341100',
        'background': '#111319',
        'secondary-container': '#ec6a06',
        'primary-fixed-dim': '#89ceff',
        'on-secondary-container': '#4a1c00',
        'on-surface': '#e2e2ea',
        'secondary': '#ffb690',
        'on-tertiary': '#003915',
        'secondary-fixed': '#ffdbca',
        'error-container': '#93000a',
        'tertiary-fixed-dim': '#4ae176',
        'tertiary-container': '#00b351',
        'on-tertiary-fixed-variant': '#005321',
        'outline': '#88929b',
        'on-secondary-fixed-variant': '#783200',
        'inverse-on-surface': '#2e3037',
        'on-primary': '#00344d',
        'primary-container': '#0ea5e9',
        'tertiary': '#4ae176',
        'tertiary-fixed': '#6bff8f',
        'surface-dim': '#111319',
        'surface-container-highest': '#33353b',
        'surface-container-high': '#282a30',
        'primary-fixed': '#c9e6ff',
        'surface-bright': '#37393f',
        'inverse-surface': '#e2e2ea',
        'on-tertiary-container': '#003c16',
        'primary': '#89ceff',
        'on-primary-container': '#003751',
        'surface-container-lowest': '#0c0e14',
        'inverse-primary': '#006591',
        'on-error': '#690005',
        'on-tertiary-fixed': '#002109',
        'surface': '#111319',
        'on-secondary': '#552100',
        'on-error-container': '#ffdad6',
        'surface-variant': '#33353b',
        'on-background': '#e2e2ea',
        'error': '#ffb4ab',
        'outline-variant': '#3e4850',
        'on-primary-fixed': '#001e2f',
        'on-surface-variant': '#bec8d2',
        'surface-container': '#1d1f25',
        'deck-dark': '#08080a',
        'deck-card': '#111115',
        'deck-surface': '#18181e',
        'deck-border': '#26262e',
        'deck-hover': '#1f2027',
      },
      spacing: {
        'track-h-compact': '24px',
        'meter-w': '12px',
        'header-transport-h': '44px',
        'pad-micro': '2px',
        'dock-splitter-thickness': '4px',
        'track-h-expanded': '72px',
        'pad-md': '12px',
        'pad-lg': '16px',
        'fader-travel': '180px',
        'track-h-standard': '36px',
        'channel-w-wide': '120px',
        'channel-w-narrow': '48px',
        'pad-xs': '4px',
        'channel-w-standard': '76px',
        'pad-sm': '8px',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem'
      },
      fontFamily: {
        'mono': ['JetBrains Mono', 'Fira Code', 'Cascadia Code', 'monospace'],
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
        'body-sm': ['Inter', 'system-ui', 'sans-serif'],
        'headline-lg': ['Inter', 'system-ui', 'sans-serif'],
        'headline-md': ['Inter', 'system-ui', 'sans-serif'],
        'headline-sm': ['Inter', 'system-ui', 'sans-serif'],
        'label-lg': ['JetBrains Mono', 'monospace'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'meter-tick': ['JetBrains Mono', 'monospace'],
        'timecode-display': ['JetBrains Mono', 'monospace'],
        'timecode-sub': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-lg': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'body-md': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'body-sm': ['11px', { lineHeight: '14px', fontWeight: '400' }],
        'headline-lg': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-md': ['15px', { lineHeight: '20px', fontWeight: '600' }],
        'headline-sm': ['13px', { lineHeight: '18px', fontWeight: '600' }],
        'label-lg': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-md': ['11px', { lineHeight: '14px', fontWeight: '500' }],
        'label-sm': ['10px', { lineHeight: '12px', fontWeight: '500' }],
        'meter-tick': ['9px', { lineHeight: '10px', fontWeight: '400' }],
        'timecode-display': ['22px', { lineHeight: '26px', fontWeight: '700', letterSpacing: '0.04em' }],
        'timecode-sub': ['13px', { lineHeight: '16px', fontWeight: '600' }],
      }
    },
  },
  plugins: [],
};
